#  To install new packages, use command: conda env update --file environment.yml --prune
name: sse_vae_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - plotly
  - seaborn
  - SciencePlots
  - jupyter
  - pip
  - scikit-learn
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch
    - torchvision
